In [1]:
import openml
import pandas as pd

DATASET_ID = 21

dataset = openml.datasets.get_dataset(DATASET_ID)

X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format="dataframe",
    target=dataset.default_target_attribute
)

print(X.shape, y.shape)
print("Categorical features:", sum(categorical_indicator))

(1728, 6) (1728,)
Categorical features: 6

In [5]:
df = X.merge(y, left_index=True, right_index=True)
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [6]:
df['class'].value_counts()

class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [2]:
attribute_names

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']

In [3]:
datasets_df = openml.datasets.list_datasets(output_format="dataframe")

In [6]:
datasets_df

,did,name,version,uploader,status,format,MajorityClassSize,MaxNominalAttDistinctValues,MinorityClassSize,NumberOfClasses,NumberOfFeatures,NumberOfInstances,NumberOfInstancesWithMissingValues,NumberOfMissingValues,NumberOfNumericFeatures,NumberOfSymbolicFeatures
2,2,anneal,1,1,active,ARFF,684.0,7.0,8.0,5.0,39.0,898.0,898.0,22175.0,6.0,33.0
3,3,kr-vs-kp,1,1,active,ARFF,1669.0,3.0,1527.0,2.0,37.0,3196.0,0.0,0.0,0.0,37.0
4,4,labor,1,1,active,ARFF,37.0,3.0,20.0,2.0,17.0,57.0,56.0,326.0,8.0,9.0
5,5,arrhythmia,1,1,active,ARFF,245.0,13.0,2.0,13.0,280.0,452.0,384.0,408.0,206.0,74.0
6,6,letter,1,1,active,ARFF,813.0,26.0,734.0,26.0,17.0,20000.0,0.0,0.0,16.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47143,47143,dummy_edit_test_dataset_ipynb,2,53508,active,arff,NaN,NaN,NaN,0.0,2.0,3.0,0.0,0.0,2.0,0.0
47144,47144,dummy_edit_test_dataset_ipynb,3,53508,active,arff,NaN,NaN,NaN,0.0,2.0,3.0,0.0,0.0,2.0,0.0
47145,47145,dummy_edit_test_dataset_ipynb,4,53508,active,arff,NaN,NaN,NaN,0.0,2.0,3.0,0.0,0.0,2.0,0.0
47146,47146,dummy_edit_test_dataset_ipynb,5,53508,active,arff,NaN,NaN,NaN,0.0,2.0,3.0,0.0,0.0,2.0,0.0
47147,47147,dummy_edit_test_dataset_ipynb,6,53508,active,arff,NaN,NaN,NaN,0.0,2.0,3.0,0.0,0.0,2.0,0.0